title: pDrift
baseURL: /
params:
  footer:
    subscribe_title: Subscribe
    subscribe_content: Stay up to date with our latest developments.
    has_subscribe: false
    social_title: About
    tagline: 'pdrift: product 2.0'
    logo_img: images/logo_alt.png
    has_social: true
    content: '&copy; pdrift. All rights reserved.'
    links:
      - new_window: true
        text: Made with Stackbit
        url: 'https://www.stackbit.com'
    nav_title: Company
    has_nav: true
  header:
    has_nav: true
    logo_img: images/logo.png
    title: pdrift
    menu:
      actions:
        - label: Newsletter
          url: /signup
  palette: navy
menu:
  main:
    - identifier: Topics
      name: Friction
      url: '%'
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
